---
# tasks file for codedeploy
- name: Install ruby
  apt:
    pkg:
      - ruby

- name: Download the AWS CodeDeploy Agent install script
  get_url:
    url: https://aws-codedeploy-ap-northeast-2.s3.amazonaws.com/latest/install
    dest: /tmp/install
    mode: "0100"

- name: Run a install script
  ansible.builtin.script: /tmp/install auto
