---
# tasks file for mysql-client

- name: Install mysql
  apt:
    pkg:
      - mysql-client

- name: create a new user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: "gatmauel_prod.*:ALL,GRANT"
    host: "{{ rds_endpoint }}"
    state: present
