---
# tasks file for mysql-client

- name: Install mysql-client
  apt:
    pkg:
      - python-pymysql

- name: create a new user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ rds_endpoint }}"
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: "gatmauel_prod.*:ALL,GRANT"
    state: present
