---
# tasks file for mysql-client

- name: Install mysql
  apt:
    pkg:
      - mysql-client

- name: create a new user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_user_db_name }}.*:ALL,GRANT"
    host: "{{ rds_endpoint }}"
    state: present
